org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
neo_version=26.3.0.52
loader_version_range=[1,)

mod_id=ferronexus
mod_name=Ferronexus
mod_license=All Rights Reserved
mod_version=0.2.0
mod_group_id=com.aigiz010.ferronexus
mod_authors=aigiz010
mod_description=Industrial tech mod: RF machines that accept any energy, ore processing, gases, multi-channel Nexus buses and the Imprinter.
